### ISSUE TITLE
New docker-compose not working?

### ISSUE THREAD

**Issue by johanbaaij** [wharsojo/myboot2docker#2]
For me it didn't, fresh boot2docker-windows install (latest) on Windows 8.1. Replacing the docker-compose file in ~MYBOOT2DOCKER/usr/local/bin with the previous one fixed it for me.

Otherwise I got this error: zsh: exec format error: docker-compose

**Comment by wharsojo** [comment]
docker-compose is fixed, you can try it.
![corrupted-docker-compose-fixed](https://cloud.githubusercontent.com/assets/11621/9021846/4b162be0-388c-11e5-9fea-e482e04d1aaa.gif)
