### ISSUE TITLE
docker-compose 1.4 released

### ISSUE THREAD

**Issue by princemaple** [wharsojo/myboot2docker#3]
@wharsojo 
love this project.

**Comment by wharsojo** [comment]
docker-compose updated to v1.4.2

![screen shot 2015-09-24 at 9 27 42 am](https://cloud.githubusercontent.com/assets/11621/10063306/ca7e2c8e-629e-11e5-9a4a-3053a0c46f7c.png)

**Comment by princemaple** [comment]
Thanks!
